# Generated by Django 4.2.11 on 2025-11-29 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_user_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Quantidade')),
                ('transaction_type', models.CharField(choices=[('daily_reward', 'Recompensa Diária'), ('purchase', 'Compra'), ('win', 'Ganho'), ('bonus', 'Bônus'), ('refund', 'Reembolso')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.user', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_claim', models.DateTimeField(blank=True, null=True, verbose_name='Última Coleta')),
                ('streak', models.PositiveIntegerField(default=0, verbose_name='Sequência de Dias')),
                ('daily_amount', models.PositiveIntegerField(default=100, verbose_name='Quantidade Diária')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_coin', to='users.user', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Moeda Diária',
                'verbose_name_plural': 'Moedas Diárias',
            },
        ),
    ]
