# Generated by Django 4.2.11 on 2025-11-29 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coins',
        ),
    ]
